
module.exports = {
    "booleans":true,
    "builtIns":true,
    "consecutiveAdds":true,
    "deadcode":true,
    "evaluate":false,
    "flipComparisons":true,
    "guards":true,
    "infinity":true,
    "memberExpressions":true,
    "mergeVars":true,
    "numericLiterals":true,
    "propertyLiterals":true,
    "regexpConstructors":true,
    "replace":true,
    "simplify":true,
    "simplifyComparisons":true,
    "typeConstructors":true,
    "removeConsole":false,
    "removeDebugger":false,
    "removeUndefined":true,
    "undefinedToVoid":true,
    "mangle": true,
    "keepFnName": true
};
